config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index', as: 'welcome'

  root to:'pages#index'
  get 'pages/index'

  get 'welcome/index'
  post 'admin/login', to: 'admin#login'
  get 'admin/logout', to: 'admin#logout'

  get 'admin/home', to:'admin#admin'
  
  get 'admin/president_new', to: 'admin#president_new'
  post 'admin/president_add', to: 'admin#president_add'
  
  get 'admin/president_edit/:id', to: 'admin#president_edit', as: 'admin_president_edit'
  patch 'admin/president_update/:id', to: 'admin#president_update', as: 'admin_president_update'
  
  get 'admin/president_view/:id', to: 'admin#president_view', as: 'admin_president'
  delete 'admin/president_delete/:id', to: 'admin#president_delete', as: 'admin_president_delete'
  
  get 'admin/president_list', to: 'admin#president_list' 
  
  get 'admin/video_new', to: 'admin#video_new'
  post 'admin/video_add', to: 'admin#video_add'
  
  get 'admin/video_edit/:id', to: 'admin#video_edit', as: 'admin_video_edit'
  patch 'admin/video_update/:id', to: 'admin#video_update', as: 'admin_video_update'
  
  get 'admin/video_view/:id', to: 'admin#video_view', as: 'admin_video'
  delete 'admin/video_delete/:id', to: 'admin#video_delete', as: 'admin_video_delete'
  
  get 'admin/video_list', to: 'admin#video_list' 
  
  delete 'admin/comment_delete/:id', to: 'admin#comment_delete', as: 'admin_comment_delete'
  
  get 'video_view/:id', to: 'video#video_view', as: 'video'
  get 'video_view/:id1/:id2', to: 'video#video_view2', as: 'video2'
  post 'video/comment_add1/:id1/:id2', to: 'video#comment_add1', as: 'comment_add1'
  post 'video/comment_add2/:id1/:id2', to: 'video#comment_add2', as: 'comment_add2'
  
  get 'video/:video_id/comment', to: 'video#comment_list', as: 'comment_list'
  post 'video/:video_id/comment_add', to: 'video#comment_add', as: 'comment_add'

  post 'welcome/get_options', to: 'welcome#get_options'

 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :video
end

app/models/president.rb
class President < ActiveRecord::Base
  has_many :videos
    validates :name, presence: true
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :comments
    validates :title, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate
  skip_before_action :authenticate, only: [:login]  
  
  def login
    @usrerr = ''
    @pswerr = ''
    if (defined? params[:login]) && (params[:login][:username] == 'admin') && (defined? params[:login]) && (params[:login][:password] == 'pass')
      session[:user_id] = 'admin'
      redirect_to :action => 'admin'
    else
        if (params[:login][:username] != 'admin')
          @usrerr = 'Input Error.'
        end
        if (params[:login][:password] != 'pass')
          @pswerr = 'Input Error.'
        end
      redirect_to :action => 'index', :controller => 'welcome', :usrerr => @usrerr, :pswerr => @pswerr
    end
  end
  
  def logout
    session[:user_id] = nil
    redirect_to :action => 'index', :controller => 'welcome'
  end
  
  def admin
    render 'home'
  end
  def president_new
  end
  def president_add
    #president_params[:supportNo] = 0
    @president = President.new(president_params)

    @president.save
    redirect_to :action => 'president_view', :id => @president[:id]
    #redirect_to @president
  end
  def president_edit
    @president = President.find(params[:id])
  end
  def president_update
    @president = President.find(params[:id])
    if @president.update(president_params)
      redirect_to :action => 'president_view', :id => @president[:id]
    end  
  end
  def president_view
    @president = President.find(params[:id])
  end
  def president_delete
    @president = President.find(params[:id])
    @president.destroy
    redirect_to admin_president_list_path
  end
  def president_list
    @presidents = President.all
  end
  
  private
  def president_params
    params.require(:president).permit(:name, :party, :wiki)
  end
  public
  
  
  def video_new
  end
  def video_add
    @video = Video.new(video_params)

    @video.save
    redirect_to :action => 'video_view', :id => @video[:id]
  end
  private
  def video_params
    params.require(:video).permit(:title, :topic, :president, :embed, :pic)
  end
  public
  def video_edit
    @video = Video.find(params[:id])
    @comments = Comment.where('video_id ==' + params[:id])
  end
  def video_update
    @video = Video.find(params[:id])
    if @video.update(video_params)
      redirect_to :action => 'video_view', :id => @video[:id]
    end  
  end
  def video_view
    @video = Video.find(params[:id])
  end
  def video_delete
    @video = Video.find(params[:id])
    sql = "delete from comments where video_id = #{params[:id]};"
 		ActiveRecord::Base.connection.update(sql)
    @video.destroy
    redirect_to admin_video_list_path
  end
  def video_list
    @videos = Video.all
  end
  
  def comment_delete
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_video_edit_path(@comment.video_id)
  end


  private
  def authenticate
    if session[:user_id].nil?
      redirect_to :action => 'index', :controller => 'welcome'
    end
  end
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
  def video_view
    @video = Video.find(params[:id])
    @president = President.where(name: @video.president).take
    @comments = @video.comments
  end
  
  def video_view2
		@video1 = Video.find(params[:id1])
		@video2 = Video.find(params[:id2])
		@president1 = President.where(name: @video1.president).take
		@president2 = President.where(name: @video2.president).take
		@comments1 = @video1.comments
		@comments2 = @video2.comments
  end
  
  def comment_add
    @video = Video.find(params[:video_id])
    @comment = @video.comments.new(comment_params)
    if @comment.score.nil?
    	@comment.score = 50
    end
    @comment.save
    redirect_to :action => 'video_view', :id => params[:video_id]
  end
  
  def comment_add1
    @video = Video.find(params[:id1])
    @comment = @video.comments.new(comment_params)
   	if @comment.score.nil?
    	@comment.score = 50
    end
    @comment.save
    redirect_to :action => 'video_view2', :id1 => params[:id1], :id2 => params[:id2]
  end
  
  def comment_add2
    @video = Video.find(params[:id2])
    @comment = @video.comments.new(comment_params2)
    if @comment.score.nil?
    	@comment.score = 50
    end
    @comment.save
    redirect_to :action => 'video_view2', :id1 => params[:id1], :id2 => params[:id2]
  end
  
  private 
  def comment_params
    params.require(:comment).permit(:content, :gender, :age, :score, :video_id)
  end
  def comment_params2
    params.require(:comment2).permit(:content, :gender, :age, :score, :video_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @videos = Video.all
    @topics = Video.select(:topic).distinct
    @usrerr = params[:usrerr] if params[:usrerr] != ''
    @pswerr = params[:pswerr] if params[:pswerr] != ''    
    @comments = Comment.group(:video_id).average(:score).sort_by{|v|v[1]}.reverse.take(6)
  end
  
 	def get_options
    options = ""
    @president = Video.where(topic: (params[:topic]))
    @president.each do |s|
      options << "<option value=#{s.id}>#{s.president}</option>"
    end
    render :text => options
  end 
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/home.html.erb
<html>
<head>
   <meta name="Unknown Team" http-equiv="Content-Type" content="text/html; charset=gb2312" />
   <%= stylesheet_link_tag "admin" %>
</head>

<body>

<div class="container">

	<div class = "jumbotron">
		<h2>Admin Home</h2>
	</div>

	<div class="row">
    	<div class="col-md-6">
        	<div class="thumbnail">
        		<!--
				<%= link_to image_tag("party.jpg", alt: "Presidents") %>
				-->
				<h3 class="page-header">Presidents</h3>
				
				
				<%=link_to admin_president_new_path, class:"btn btn-primary" do%>
					<i class="glyphicon glyphicon-plus">Add</i>
				<%end%>
								
				
				<%=link_to admin_president_list_path, class:"btn btn-primary" do%>
  					<i class="glyphicon glyphicon-th-list">List</i>
  				<% end %>
            </div>    
        </div>
        <div class="col-md-6">
        	<div class="thumbnail">
            	<h3 class="page-header">Videos</h3>
				
				
				<%=link_to admin_video_new_path, class:"btn btn-primary" do%>
					<i class="glyphicon glyphicon-plus">Add</i>
				<%end%>
								
				
				<%=link_to admin_video_list_path, class:"btn btn-primary" do%>
  					<i class="glyphicon glyphicon-th-list">List</i>
  				<% end %>
				
            </div>
        </div>
				
				<%= link_to admin_logout_path, class:"btn btn-primary" do%>
					<i class="glyphicon glyphicon-circle-arrow-left"> Logout</i>
				<%end%>

					

        <!--
        <div class="col-md-4">
            <div class="thumbnail">
            	<img src="http://goo.gl/0Kd7UO">
            </div>
        </div>
        -->
    </div>


</div>


</body>

</html>

app/views/admin/president_edit.html.erb
<html>

<head>
	<meta name="Unknown Team" http-equiv="Content-Type" content="text/html; charset=gb2312" />
 	<%= stylesheet_link_tag "admin" %>
</head>

<body class="container">

	<h1 class = "jumbotron">Add President</h1>
	<%= form_for :president, url: admin_president_update_path(@president), method: :patch do |f| %>
  	<p>
    	<%= f.label :name %><br>
    	<%= f.text_field :name %>
  	</p>
	
	<div class="btn-group">
  		<%= f.label :party %> <br>
	
  		<%= f.select(:party, [["Republican", "Republican"], ["Democratic", "Democratic"],["Others","Others"]], {}, {class: "form-control"}) %>
	</div>
  	
  	<p>
    	<%= f.label :wiki %><br>
    	<%= f.text_area :wiki, :cols=>"100",:rows=>"10" %>
  	</p>
 
  	<p>
    	<%= f.submit %>
  	</p>
	<% end %>

	<%= link_to admin_president_list_path, class:"btn btn-primary" do %>
		<i class="glyphicon glyphicon-circle-arrow-left">Back</i>
	<%end%>

</body>
</html>

app/views/admin/president_list.html.erb
<html>

<head>
	<meta name="Unknown Team" http-equiv="Content-Type" content="text/html; charset=gb2312" />
 	<%= stylesheet_link_tag "admin" %>
</head>


<body class="container">


	<h1 class="jumbotron">Presidents List</h1>
	


	<table class="table">
  		
 		<thread>
			<tr>
	            <th>Name</th>
	            <th>Party</th>
	            <th>Wiki</th>
	        </tr> 		
 		
  			<% @presidents.each do |president| %>
    		<tr>
      		<td><%= president.name %></td>
      		<td><%= president.party %></td>
			<td><%= president.wiki %></td>
			<td><%= link_to 'Show', admin_president_path(president)%></td>
			<td><%= link_to 'Edit', admin_president_edit_path(president)%></td>
			<td><%= link_to 'Destroy', admin_president_delete_path(president),
			                    method: :delete %></td>
    		</tr>
  			<% end %>
  		</thread>
	</table>


	
	
	<%= link_to admin_home_path, class:"btn btn-primary" do%>
		<i class="glyphicon glyphicon-circle-arrow-left"> Back</i>
	<%end%>
	
</body>
</html>

app/views/admin/president_new.html.erb
<html>

<head>
   <meta name="Unknown Team" http-equiv="Content-Type" content="text/html; charset=gb2312" />
   <%= stylesheet_link_tag "admin" %>
</head>


<body class="container">

	<h1 class="jumbotron">Add President</h1>
	
	<%= form_for :president, url: admin_president_add_path do |f| %>
 	
 	<p>
    	<%= f.label :name %><br>
    	<%= f.text_field :name %>
  	</p>
	
	<div class="btn-group">
  		<%= f.label :party %> <br>
	
  		<%= f.select(:party, [["Republican", "Republican"], ["Democratic", "Democratic"],["Others","Others"]], {}, {class: "form-control"}) %>
	</div>

 
  	<p>
    	<%= f.label :wiki %><br>
    	<%= f.text_area :wiki, :cols=>"100",:rows=>"10" %>
  	</p>
 
  	<p>
  	 	<%= f.submit %>
  	</p>
	<% end %>
	
	<%= link_to admin_home_path, class:"btn btn-primary" do %>
		<i class="glyphicon glyphicon-circle-arrow-left">Back</i>
	<%end%>


 
 
</body>
</html>

app/views/admin/president_view.html.erb
<html>
<head>
   <meta name="Unknown Team" http-equiv="Content-Type" content="text/html; charset=gb2312" />
   <%= stylesheet_link_tag "admin" %>
</head>



<body class="container">

	<h1 class="jumbotron">President</h2>

	<p>
  		<strong>Name:</strong>
  		<%= @president.name %>
	</p>
 
	<p>
  		<strong>Party:</strong>
  		<%= @president.party %>
	</p>

	<p>
  		<strong>Wiki:</strong>
  		<%= @president.wiki %>
	</p>
	
	<%= link_to admin_president_list_path, class:"btn btn-primary" do %>
		<i class="glyphicon glyphicon-circle-arrow-left">Back</i>
	<%end%>


</body>
</html>

app/views/admin/video_edit.html.erb
<html>

<head>
	<meta name="Unknown Team" http-equiv="Content-Type" content="text/html; charset=gb2312" />
 	<%= stylesheet_link_tag "admin" %>
</head>

<body class="container">


<h1 class ="jumbotron">Edit Video</h1>

<%= form_for :video, url: admin_video_update_path(@video), method: :patch do |f| %>
  	<p>
    	<%= f.label :title %><br>
    	<%= f.text_field :title %>
  	</p>
	
  	<p>
    	<%= f.label :topic %><br>
    	<%= f.text_field :topic %>
  	</p>
 
  	<div class="btn-group">
    	<%= f.label :president %><br>
    	<%= f.select(:president, President.select(:name).distinct.collect {|p| [ p.name, p.name]},   {}, {class: "form-control"}) %>
  	</div>
	
  	<p>
    	<%= f.label :pic %><br>
    	<%= f.text_field :pic %>
  	</p>
  	
  	<p>
    	<%= f.label :embed %><br>
    	<%= f.text_area :embed, :cols=>"100", :rows=>"10" %>
  	</p>
	
  	
 
  	<p>
    	<%= f.submit %>
  	</p>
	<% end %>


	<%= link_to admin_video_list_path, class:"btn btn-primary" do %>
		<i class="glyphicon glyphicon-circle-arrow-left">Back</i>
	<%end%>
	
<h2>Comment Management</h2>
<table class="table">
	<% @comments.each do |c| %>
	<tr>
			<td><%= c.created_at %></td>
			<td><%= c.content %></td>
	<td><%= link_to 'Delete', admin_comment_delete_path(c), method: :delete %></td>
	</tr>
	<% end %>
</table>	
	
</body>
</html>

app/views/admin/video_list.html.erb
<html>
<head>
	<meta name="Unknown Team" http-equiv="Content-Type" content="text/html; charset=gb2312" />
 	<%= stylesheet_link_tag "admin" %>
</head>
<body>

<div class="container">

	<div class="jumbotron">	
		<h1>Videos List</h1>
	</div>
	
	<table class="table">
  		<thread>
  			<tr>
    			<th>Title</th>
    			<th>Topic</th>
				<th>President</th>
  			</tr>
 
  			<% @videos.each do |video| %>
    		<tr>
      			<td><%= video.title %></td>
      			<td><%= video.topic %></td>
				<td><%= video.president %></td>
				<td><%= link_to 'Show', admin_video_path(video)%></td>
				<td><%= link_to 'Edit', admin_video_edit_path(video)%></td>
				<td><%= link_to 'Destroy', admin_video_delete_path(video),
			                    method: :delete %></td>
    		</tr>
  			<% end %>
  		</thread>
	</table>

	<%= link_to admin_home_path, class:"btn btn-primary" do%>
		<i class="glyphicon glyphicon-circle-arrow-left">Back</i>
	<%end%>
	
</div>

</body>
</html>

app/views/admin/video_new.html.erb
<html>
<head>
	<meta name="Unknown Team" http-equiv="Content-Type" content="text/html; charset=gb2312" />
 	<%= stylesheet_link_tag "admin" %>
</head>


<body class="container">

<h1 class="jumbotron">Add Video</h1>

<%= form_for :video, url: admin_video_add_path do |f| %>
  	<p>
    	<%= f.label :title %><br>
    	<%= f.text_field :title %>
  	</p>
	
  	<p>
    	<%= f.label :topic %><br>
    	<%= f.text_field :topic %>
  	</p>
 
  	<div class="btn-group">
    	<%= f.label :president %><br>
    	<%= f.select(:president, President.select(:name).distinct.collect {|p| [ p.name, p.name]}, {}, {class: "form-control"}   ) %>
  	</div>
	
  	<p>
    	<%= f.label :pic %><br>
    	<%= f.text_field :pic %>
  	</p>
 
  	<p>
    	<%= f.label :embed %><br>
    	<%= f.text_area :embed, :cols=>"100",:rows=>"10" %>
  	</p>
  	
  	<p>
   		<%= f.submit %>
  	</p>
	<% end %>
	
	<%= link_to admin_home_path, class:"btn btn-primary" do %>
		<i class="glyphicon glyphicon-circle-arrow-left">Back</i>
	<%end%>


</body>
</html>

app/views/admin/video_view.html.erb
<html>
<head>
   <meta name="Unknown Team" http-equiv="Content-Type" content="text/html; charset=gb2312" />
   <%= stylesheet_link_tag "admin" %>
</head>


<body class="container">

	<h1 class="jumbotron">Video</h1>

	<p>
  		<strong>Title:</strong>
  		<%= @video.title %>
	</p>
 
	<p>
  		<strong>Topic:</strong>
  		<%= @video.topic %>
	</p>

	<p>
  		<strong>President:</strong>
  		<%= @video.president %>
	</p>

	<p>
  		<%= @video.embed.html_safe %>
	</p>



	<%= link_to admin_video_list_path, class:"btn btn-primary" do %>
		<i class="glyphicon glyphicon-circle-arrow-left">Back</i>
	<%end%>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PresidentDebate</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  
  <body>

    <div>
      <%= yield %>
    </div>
  </body>
  
</html>

app/views/video/video_view.html.erb
	<html>
	<head>
	   <meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
	   <title>President Debate Videos</title>
	   <script src="CJL.0.1.min.js"></script>
	   <script src="rotate.js"></script>
	   <%= stylesheet_link_tag "video" %>
	   <h2> &nbsp;&nbsp;The Mashup <abbr title="Cascading Style Sheets"></abbr> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Debate</h2>
	   	   	   <a href="#" class="myButton" onclick="window.location.href= '/'">Back</a>
	</head>

	<body background="">
	<div class="page-wrapper">
	<div class="main supporting" id="zen-supporting" role="main">

		<h3>
		<strong>Debate Video Title:</strong>
		<%= @video.title %>
		</h3>
  	<br>
  	  	<br>
		<p>
	  		<%= @video.embed.html_safe %>
		</p>
		<p>
	 	 <strong>Debate Topic:</strong>
	  	<%= @video.topic %>
	  	<br>
	  	<br>
	 	<strong>Debate President:</strong>
	 	  <%= @video.president %>
	 	  <%= link_to image_tag('wiki.png', size: "20x20"), 'http://'+@president.wiki %>
		</p>
  	<br>
  	  	<br>

	<h3>
	<strong>Leave Your Comment Below:</strong>
	</h3>
	  <p> </p>
      <div style="float:left">
	<%= form_for :comment, url: comment_add_path(@video) do |f| %>
	  <p> </p>
	  <p>
	    <%= f.label :comment %><br>
	    <%= f.text_area :content %>
	  </p>
	  <p>
    	<%= f.label :gender %><br>
    	<%= f.label :gender, "male", :value => "male"  %>
    	<%= f.radio_button :gender, "male" %>
    	<%= f.label :gender, "female", :value => "female" %>
    	<%= f.radio_button :gender, "female", :checked => true %>
    </p>
	  <p>
		<%= f.select(:age, [["under 20 years old", "10"], ["20-30 years old", "20"], ["30-40 years old", "30"], ["40-50 years old", "40"], ["50-60 years old", "50"],  ["over 60 years old", "60"]] ) %>
	  </p>
  	  <p>
	  <%= f.submit %>	  
	  </p>  
	 </div>
         <div style="float:left; left:500px;">
	  <div style="visibility:hidden;">  <%= f.text_field :score %></div>
	  <p id="score">
	  <%= f.label :score %>
	  </p>

	  <div id="idContainer1"> 
           <style>
            #idContainer1{border:0px solid #000;width:128px; height:118px; background: center no-repeat;  border-radius:56px;
  overflow:hidden; cursor:pointer;}
          </style>
	  <script>
	    (function(){
	                 var container = $$("idContainer1"), src = "http://imageshack.com/a/img538/6042/ERrlXE.png"
		         it = new ImageTrans1(container,"score");
	                 it.load(src);
	               })()
	  </script>

	</div>
	<p>Score Range: 1-100</p>
	<% end %>
	</div>

<div class = "comments" style="clear: both;">
	<h3> <strong>ALL COMMENTS</strong></h3>
	<% @comments.each do |comment| %>
		  <p> </p>
	  <p>
	    <strong><%= comment.created_at %></strong><br>
	    <%= comment.content %>
	    [score: <%= comment.score %>]
	  </p>
	<% end %>
</div>


	</div>
	</div>

	</body>
	</html>

app/views/welcome/index.html.erb
<html>

<head>
   <meta name="Unknown Team" http-equiv="Content-Type" content="text/html; charset=gb2312" />
	<%= stylesheet_link_tag "welcome" %>
</head>


<body>


<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
      		<a class="navbar-brand">Presidential Debate Mashup</a>
    	</div>
				<%= form_for :login, url: admin_login_path, :class => "form-inline"  do |f|%>    	
    	
  			
    	<ul class="nav navbar-nav">

        <li class="active"><a>ADMIN LOGIN &nbsp;&nbsp;|</a></li>       		
        	
				<li class="active"><a> UserName</a></li>
        <li>	
    			<%= f.text_field :username, :class=>"form-control",:placeholder=>"Username#{@usrerr}",:style=>"height:50px;" %>
				</li>
				
				<li class="active"><a> PASSWORD</a></li>
				<li>
    			<%= f.password_field :password, :class=>"form-control",:placeholder=>"Password#{@pswerr}",:style=>"height:50px;" %>
				</li>
				
  		</ul>
			
			<ul class="nav navbar-nav navbar-right">
				<%= f.submit "Login", :class=>"btn btn-default",:style=>"height:50px; margin-right:50px;"   %>
			</ul>
	
	
		<% end %>
		
	</div>
</nav>




<script type="text/javascript">
  function get_options(value){
    $.ajax({
      type: "POST",
      url:'/welcome/get_options?topic='+value,
      data:'text',
      success: function(data){
        $("#president1").html(data);
        $("#president2").html(data);
      }
    })
  }
</script>

<!-- -->
<div class="main supporting" id="zen-supporting" role="main">
	<div class="recommanded jumbotron">
		<h3>Recommend Videos</h3>
		<% @comments.each do |v| %>
		<%= link_to image_tag(@videos.find(v[0]).pic, :class => "container"), video_path(@videos.find(v[0])) %> <br>
		<p style="text-align:center; font-size:12pt; font-family:Georgia;color:black; "> <%=@videos.find(v[0]).title%></p>
		<br><br>
		<% end %>		
	</div>
</div>



<div class="page-wrapper">
	<div class="summary" id="zen-summary" role="article">
		<p>This website is a production of Texas A&M University</p>
			
	</div>

	<div class="main supporting" id="zen-supporting" role="main">
		<div class="explanation" id="zen-explanation" role="article">
			
			
	    <h3 class="active">Please Select One Topic You Like</h3>        		
	    <div class="styled-select">
	    <%= select_tag :topic, options_for_select(@topics.collect{|c| [c.topic, c.topic]}), prompt: " Please select a topic", :onchange => "get_options(this.value)" , :class=>"form-control", :style=>"height:50px;"%>
			</div>
        	
	    <h3 class="active">Please Select The First President</h3>        		
	    <div class="styled-select">
				<%= select_tag :president1, "<option value=\"-1\"> Please select one president</option>".html_safe, :class=>"form-control", :style=>"height:50px;"%>
			</div>
			
			<h3 class="active">Please Select The Second President</h3>
			<div class="styled-select">	
			<%= select_tag :president2, "<option value=\"-1\"> Please select another president</option>".html_safe, :class=>"form-control", :style=>"height:50px;"%>
			</div>
			<br>


			<input class="viewButton2" type="button" value="View Videos" onclick="checkroute()"/>	<br><br>
			
			
			<script type="text/javascript">
        		function checkroute() {
        		var video1 = document.getElementById('president1').options[document.getElementById('president1').selectedIndex].value;
        		var video2 = document.getElementById('president2').options[document.getElementById('president2').selectedIndex].value;
        		var path;
				if (video1 == video2 && video1 > 0) {
        			path = '/video_view/'+video1;
        			window.location.href = path;
        		}
        		else if (video1 > 0 && video2 > 0){
        			path =  '/video_view/'+video1+'/'+video2;
        			window.location.href = path;
          		}
          		else {
        			alert("Please choose topic and president");
        		}
        	}
			</script>
			
			
			
			
			<h3>Republican or Democratic?</h3>
			<div id="banner">
				<div><a href='http://www.svgop.com/files/Differences%20Between%20Republicans%20and%20Democrats.pdf' target=_blank> <img src="http://1.bp.blogspot.com/-WuxMlJySQ4w/TfqfME7-7WI/AAAAAAAACag/YUQcrbNtbpI/s1600/morin.jpg" alt="Skyline 1" height='270' width='460'/> </a></div>
				<div><a href='http://www.svgop.com/files/Differences%20Between%20Republicans%20and%20Democrats.pdf' target=_blank>  <img src="https://www.multistate.com/insider/wp-content/uploads/2012/11/republican-democrat-battle.jpg" alt="Skyline 3" height='270' width='450'> </a></div>
				
			</div>
			
		</div>
	</div>

</div>




</body>

</html>